name: Run E2e Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    services:
      gym-api-pg:
        image: bitnami/postgresql
        ports:
          - 5434:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: gym-api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5434/gym-api"